services:
  api:
    build: ./api
    image: product-api
    restart: on-failure
    env_file:
      - ./env/api.env
    ports:
      - 8080:8080
    networks:
      - golang-api
    depends_on:
      - db

  db:
    build: ./db/postgres
    image: db
    restart: on-failure
    env_file:
      - ./env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - golang-api

  db-migrate:
    build: ./db/migrate
    image: db-migrate
    restart: on-failure
    env_file:
      - ./env/migrate.env
    networks:
      - golang-api
    depends_on:
      - db

  kong:
    image: kong/kong-gateway
    restart: on-failure
    env_file:
      - ./env/kong.env
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    networks:
      - golang-api
    depends_on:
      - api
      - db

  kong-migrate:
    image: kong/kong-gateway
    command: kong migrations bootstrap
    restart: on-failure
    env_file:
      - ./env/kong.env
    networks:
      - golang-api
    depends_on:
      - db

  kong-configure:
    build: ./kong
    image: kong-configure
    restart: on-failure
    env_file:
      - ./env/kong-configure.env
    networks:
      - golang-api
    depends_on:
      - kong

networks:
  golang-api:
    name: golang-api

volumes:
  db:
