version: "3.9"

services:
  api:
    build: ./api/
    image: golang-api
    restart: on-failure
    env_file:
      - ../golang-api-secrets/api.env
    ports:
      - 8080:8080
    networks:
      - golang-api-net
    depends_on:
      - db

  db:
    image: postgres:13.2
    env_file:
      - ../golang-api-secrets/postgres.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - golang-api-net

  minio:
    image: minio/minio
    command: server /data
    env_file:
      - ../golang-api-secrets/minio.env
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data
    networks:
      - golang-api-net

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/etc/loki/config.yml
    command: -config.file=/etc/loki/config.yml
    networks:
      - golang-api-net
    depends_on:
      - minio

  promtail:
    image: grafana/promtail
    volumes:
      - promtail-data:/tmp/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - golang-api-net
    depends_on:
      - loki

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    env_file:
      - ../golang-api-secrets/grafana.env
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - golang-api-net

  kong:
    image: kong
    volumes:
      - ./kong.yml:/etc/kong/config.yml
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    environment:
      - KONG_DATABASE=off
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_DECLARATIVE_CONFIG=/etc/kong/config.yml
    networks:
      - golang-api-net

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ../golang-api-secrets/pgadmin.env
    ports:
      - 8011:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - golang-api-net

  swaggereditor:
    image: swaggerapi/swagger-editor
    ports:
      - 8012:8080
    networks:
      - golang-api-net

networks:
  golang-api-net:

volumes:
  db-data:
  pgadmin-data:
  minio-data:
  grafana-data:
  promtail-data:
