version: "3.9"

services:
  api:
    build: ./api
    image: api
    restart: on-failure
    env_file:
      - ./env/api.env
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - db

  db:
    build: ./db/postgres
    image: db
    restart: on-failure
    env_file:
      - ./env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

  db-migrate:
    build: ./db/migrate
    image: db-migrate
    restart: on-failure
    env_file:
      - ./env/migrate.env
    networks:
      - backend
    depends_on:
      - db

  kong:
    image: kong/kong-gateway
    restart: on-failure
    env_file:
      - ./env/kong.env
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004
    networks:
      - backend
    depends_on:
      - kong-db

  kong-db:
    image: postgres:13.2
    restart: on-failure
    env_file:
      - ./env/postgres-kong.env
    ports:
      - 5433:5432
    volumes:
      - kong-db:/var/lib/postgresql/data
    networks:
      - backend

  kong-db-migrate:
    image: kong/kong-gateway
    command: kong migrations bootstrap
    restart: on-failure
    env_file:
      - ./env/kong.env
    networks:
      - backend
    depends_on:
      - kong-db

networks:
  backend:

volumes:
  db:
  kong-db:
