version: "3.7"

services:
  api:
    build: ./api/
    image: golang-api
    env_file:
      - ../golang-api-secrets/api.env
    ports:
      - 8010:8010

  ui:
    build: ./ui/
    image: golang-api-ui
    ports:
      - 8020:80

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ../golang-api-secrets/pgadmin.env
    ports:
      - 8030:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  swaggereditor:
    image: swaggerapi/swagger-editor
    ports:
      - 8040:8080

volumes:
  pgadmin-data:
