version: "3.8"

services:
  db:
    image: postgres:13.1
    env_file:
      - ../golang-api-secrets/postgres.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - golang-api-net

  api:
    build: ./api/
    image: golang-api
    env_file:
      - ../golang-api-secrets/api.env
    ports:
      - 8010:8010
    networks:
      - golang-api-net

  ui:
    build: ./ui/
    image: golang-api-ui
    ports:
      - 8020:80
    networks:
      - golang-api-net

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ../golang-api-secrets/pgadmin.env
    ports:
      - 8030:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - golang-api-net

  swaggereditor:
    image: swaggerapi/swagger-editor
    ports:
      - 8040:8080
    networks:
      - golang-api-net

networks:
  golang-api-net:

volumes:
  db-data:
  pgadmin-data:
