version: "3.9"

services:
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
      - ./migrate.sh:/migrate.sh
    env_file:
      - ../env/migrate.env
    entrypoint: /migrate.sh
